import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# If config.py is two levels up, add it to the path so python can find it
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../config")))
import config

if config.bug_data:
    print("Bug data already loaded.")
else:
    config.bug_data = pd.read_csv(os.path.join(config.PROCESSED_DATA_DIR, 'normalized_dataset_bugs.csv'))
#Replace string with int ratings
#config.bug_data["severity"] = config.bug_data["severity"].replace({"Low": 1, "Medium": 2, "High": 3, "Critical": 4})
#config.bug_data["priority"] = config.bug_data["priority"].replace({"Low": 1, "Normal": 2, "High": 3, "Urgent": 4})

#Recode severity
def calculate_severity(row):
    score = 0
    # Environment
    if row["environment_id"] == 2:
        score += 2
    elif row["environment_id"] == 3:
        score += 1
    # Bug Category
    if row["category_id"] == 16:
        score += 4
    elif row["category_id"] in [
        2,
        15,
        9,
        4,
        12
    ]:
        score += 3
    elif row["category_id"] in [
        14,
        11,
        1,
        13,
        3
    ]:
        score += 2
    else:
        score += 1
    # Error Code
    if row["error_code"] >= 500:
        score += 2
    elif row["error_code"] >= 400:
        score += 1
    return score

#Apply recode
config.bug_data["severity_score"] = config.bug_data.apply(
    calculate_severity,
    axis=1
)

def severity_class(score):
    if score <= 2:
        return 1      # Low
    elif score <= 4:
        return 2      # Medium
    elif score <= 6:
        return 3      # High
    else:
        return 4      # Critical

config.bug_data["severity"] = config.bug_data["severity_score"].apply(severity_class)

#Recode priority
def priority_class(row):
    score = row["severity"]
    if row["environment_id"] == 2:
        score += 1
    if score >= 5:
        return 4      # P1 Critical
    elif score == 4:
        return 3      # P2 High
    elif score == 3:
        return 2      # P3 Normal
    else:
        return 1      # P4 Low

#Apply recode
config.bug_data["priority"] = config.bug_data.apply(
    priority_class,
    axis=1
)

#Export new file
config.bug_data_corrected = config.bug_data
config.bug_data_corrected.to_csv(os.path.join(config.PROCESSED_DATA_DIR, 'bug_dataset_with_priority_and_severity_corrected.csv'), index=False)


#=============================================================================================================

#Number of bugs
print("Number of bugs: ", len(config.bug_data))

#Number of errors per error_code
print("Number of errors per error_code: \n", config.bug_data["error_code"].value_counts())
# Define the order mapping (matching the IDs generated by your script)
severity_map = {1: 'Low', 2: 'Medium', 3: 'High', 4: 'Critical'}
#Number of errors per severity
print("Number of errors per severity: \n", config.bug_data["severity"].value_counts())
# Print by mapping the index numbers to names
print("Number of errors per severity:\n", config.bug_data["severity"].value_counts().rename(index=severity_map))

# Define the order mapping (matching the IDs generated by your script)
priority_map = {1: 'Low', 2: 'Normal', 3: 'High', 4: 'Urgent'}
#Number of errors per priority rating
print("Number of errors per priority rating: \n", config.bug_data["priority"].value_counts())
# Print by mapping the index numbers to names
print("Number of errors per priority rating:\n", config.bug_data["priority"].value_counts().rename(index=priority_map))


# Define the order mapping (matching the IDs generated by your script)
environment = {1: 'Development', 2: 'Production', 3: 'Staging'}
#Number of errors per environment
print("Number of errors per environment: \n", config.bug_data["environment_id"].value_counts())
# Print by mapping the index numbers to names
print("Number of errors per environment:\n", config.bug_data["environment_id"].value_counts().rename(index=environment))

#=============================================================================================================

#Severity by bug category
print("Priority by bug category: \n", config.bug_data.groupby("category_id")["priority"].mean())

#Priority by bug category
print("Severity by bug category: \n", config.bug_data.groupby("category_id")["severity"].mean())

#Severity by environment
environment_severity = config.bug_data.groupby("environment_id")["severity"].agg
print("Severity by environment: \n", config.bug_data.groupby("environment_id")["severity"].mean())

#Priority by environment
print("Priority by environment: \n", config.bug_data.groupby("environment_id")["priority"].mean())

#Severity by bug domain
print("Severity by bug domain: \n", config.bug_data.groupby("domain_id")["severity"].mean())

#Priority by bug domain
print("Priority by bug domain: \n", config.bug_data.groupby("domain_id")["priority"].mean())


#=============================================================================================================

#Bar Plot of Severity based on Bug Category
severity_by_domain = config.bug_data.groupby("category_id")["severity"].mean().sort_values(ascending=True)

plt.figure(figsize=(12, 6))
sns.barplot(x=severity_by_domain.index, y=severity_by_domain.values, palette='viridis')
plt.title('Mean Severity Rating by Bug Category')
plt.xlabel('Bug Domain')
plt.ylabel('Mean Severity Rating')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

#=============================================================================================================

#Bar Plot of Severity by environment
severity_by_environment = config.bug_data.groupby("environment_id")["severity"].median().sort_values(ascending = True)

plt.figure(figsize=(12, 6))
sns.barplot(x=severity_by_environment.index, y=severity_by_environment.values, palette='viridis')
plt.title('Median Severity Rating by Environment')
plt.xlabel('Environment')
plt.ylabel('Median Severity Rating')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

#=============================================================================================================

#Bar Plot of Priority by environment
priority_by_environment = config.bug_data.groupby("environment_id")["priority"].median().sort_values(ascending = True)

plt.figure(figsize=(12, 6))
sns.barplot(x=priority_by_environment.index, y=priority_by_environment.values, palette='viridis')
plt.title('Median Priority Rating by Environment')
plt.xlabel('Environment')
plt.ylabel('Median Priority Rating')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

#=============================================================================================================

#Scatterplot to check correlation between priority and severity ratings
fig, ax = plt.subplots(figsize = (12, 6))
ax.scatter(config.bug_data["priority"], config.bug_data["severity"])
sns.regplot(x = config.bug_data['priority'], y = config.bug_data['severity'])
plt.suptitle('Correlation Between Severity and Priority', y=1.02)
plt.xlabel('Priority Rating')
plt.ylabel('Severity Rating')
plt.tight_layout()
plt.show()

#Check correlation coefficient
correlation = config.bug_data['priority'].corr(config.bug_data['severity'])
print("Correlation between priority and severity:", correlation)

#=============================================================================================================

#Check for missing values
if config.bug_data.isna().values.any() == True:
  print("There are missing values in the dataset")
  print(config.bug_data.isna().sum())
else:
  print("There are no missing values in the dataset")

#Replace missing values with "Unknown"
config.bug_data_filled = config.bug_data.fillna("Unknown")

#Check
print(config.bug_data_filled.isna().sum())

#=============================================================================================================

#Check for duplicate values
if config.bug_data_filled.duplicated().any() == True:
  print("There are duplicate values in the dataset")
  print(config.bug_data_filled.duplicated().sum())
else:
  print("There are no duplicate values in the dataset")


#=============================================================================================================

#Combined severity/priority rating
config.bug_data_filled["severity_priority"] = (config.bug_data_filled["severity"] + config.bug_data_filled["priority"])//2